version: '3'
services:
    web:
        build: ./build/web/
        container_name: "sssr-php-apache-webserver"
        volumes:
            - "./web/html/:/var/www/html/"
        ports:
            - "80:80"
        depends_on:
            - db
        init: true
    db:
        build: ./build/db/
        container_name: "sssr-mysql-dbserver"
        volumes:
            - ./build/db/initdb.d:/docker-entrypoint-initdb.d
            - ./db/mysql/:/var/lib/mysql/
        env_file:
          - ./build/db/.env
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: "sssr-phpmyadmin"
        env_file:
          - ./build/phpmyadmin/.env
        links:
            - db
        ports:
            - 8080:80
        
